_BASE_: "Base-SparseInst.yaml"
MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 1
  WEIGHTS: "pretrained_models/R-50.pkl"
  SPARSE_INST:
    DECODER:
      NAME: "BaseIAMDecoder"
DATASETS:
  TRAIN: ("pills_train",)
  TEST: ("pills_val",)
OUTPUT_DIR: "output/sparse_inst_r50_base"
SOLVER:
  IMS_PER_BATCH: 1
#  MAX_ITER: 270000